name: "cpp linter"
on:
  push:
    branches: [ "main", "nn" ]
  pull_request:
    branches: [ "main", "nn" ]

jobs:
  linter-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Super-Linter
        uses: super-linter/super-linter@v7.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
