name: "cpp linter"

on:
  push:
    branches: [ "main", "nn" ]
  pull_request:
    branches: [ "main", "nn" ]


jobs:
  linter-build:
    runs-on: ubuntu-latest
    steps:
      - name: Super-Linter
        uses: super-linter/super-linter@v7.3.0

